---
- name: Cleanup memory
  hosts: all
  become: true

  tasks:

    - name: Memory before cleanup
      command: free -h
      register: before_memory

    - debug:
        var: before_memory.stdout_lines

    #- name: Clear tmp
     # shell: rm -rf /tmp/*

    - name: Clear apt cache
      command: apt clean

    - name: Clear RAM cache
      shell: |
        sync
        echo 3 > /proc/sys/vm/drop_caches
      args:
        executable: /bin/bash

    - name: Memory after cleanup
      command: free -h
      register: after_memory

    - debug:
        var: after_memory.stdout_lines
